### ISSUE TITLE
Missing new specs

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/sessions_controller_lab#9]
The solution is missing the 4 new specs that the student is meant to write. We definitely want to learn more about writing tests.

**Comment by maxwellbenton** [comment]
Hi there,

I'm having difficulty understanding what this issue is related to. There is currently only one spec file, `spec/controllers/session_controller_spec.rb` with 6 tests in total. 

I'm going to close it for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
